"""Regenerate research comparison offline from the preserved official artifact."""
import json
from pathlib import Path

ROOT = Path(__file__).parent
source = json.loads((ROOT / 'leaderboard-live.json').read_text())
# Site pricing transformation from index-C8-z8dCr.js, SU/NU/Iy.
PRICES = {
    'gpt-5-6-luna': ((1, .1, 6), (.2, .02, 1.2)),
    'gpt-5-6-terra': ((2.5, .25, 15), (2, .2, 12)),
    'gpt-5-6-sol': ((5, .5, 30), (4, .4, 20)),
}
EFFORTS = ['low', 'medium', 'high', 'xhigh', 'max']
MODELS = ['gpt-6-astra', 'gpt-5-6-sol', 'gpt-5-6-terra', 'gpt-5-6-luna']
rows = [dict(r) for r in source['rows'] if r['model'] in MODELS]
assert len(rows) == 20
for r in rows:
    r['display_cost'] = r['mean_cost_usd']
    if r['model'] in PRICES:
        old, new = PRICES[r['model']]
        usage = (r['mean_input_tokens'] - r['mean_cache_tokens'], r['mean_cache_tokens'], r['mean_output_tokens'])
        ratio = sum(a*b for a,b in zip(usage, new)) / sum(a*b for a,b in zip(usage, old))
        r['display_cost'] *= ratio
    peak = r['median_peak_context_tokens']
    r['context_gate'] = 'unknown' if peak is None else ('pass' if peak <= 100_000 else 'fail')
rows.sort(key=lambda r: (MODELS.index(r['model']), EFFORTS.index(r['reasoning_effort'])))

def dominates(a, b, context=False):
    av = [-a['pass_at_1'], a['display_cost'], a['mean_output_tokens']]
    bv = [-b['pass_at_1'], b['display_cost'], b['mean_output_tokens']]
    if context:
        av.append(a['median_peak_context_tokens'])
        bv.append(b['median_peak_context_tokens'])
    return all(x <= y for x,y in zip(av,bv)) and any(x < y for x,y in zip(av,bv))

def name(r):
    return r['model'] + '/' + r['reasoning_effort']

lines = ['# DeepSWE v1.1: full GPT effort comparison', '',
    'Source: https://deepswe.datacurve.ai/artifacts/v1.1/leaderboard-live.json',
    'Generated by source: ' + source['generated_at'], '',
    'All 20 GPT configurations; full 70-row source retained. Regenerate with `python3 docs/research/deepswe-refresh/analyze.py`.', '',
    '## Cost and metric semantics', '',
    '- Raw $ is recorded mean_cost_usd. Site $ reproduces the captured site transformation; it is not an independent verification of current OpenAI prices.',
    '- GPT-5.6 site costs scale raw costs by the ratio of new/old token-price estimates. The source lacks separate cache-write/reasoning fields for these rows; do not fabricate them.',
    '- Astra site costs equal raw costs. Source explicitly labels expected launch pricing: $12/M uncached input, $15/M writes, $1.20/M reads, $50/M output, plus $2/M compute units. Token-only repricing omits a real cost component.',
    '- Output, steps and duration below are means across scored attempts. Context is median of per-run peaks. Missing context is unknown, never zero.',
    '- Score uncertainty is source 95% run-to-run CI half-width over four repeated benchmark passes. Small point-estimate gains are not established significant improvements.',
    '- Pass@1 denominator excludes provider/verifier/network errors; timeouts/context failures count as failures. Preserve attempt counts and pass@4 separately.', '',
    '## Every configuration', '',
    '| Model | Effort | Pass@1 ± CI (pp) | Raw $ | Site $ | Output k | Steps | Minutes | Peak k (median) | Context gate |',
    '|---|---|---:|---:|---:|---:|---:|---:|---:|---|']
for r in rows:
    peak = 'unknown' if r['median_peak_context_tokens'] is None else f"{r['median_peak_context_tokens']/1000:.1f}"
    lines.append(f"| {r['model']} | {r['reasoning_effort']} | {100*r['pass_at_1']:.2f} ± {100*r['ci_half']:.2f} | {r['mean_cost_usd']:.3f} | {r['display_cost']:.3f} | {r['mean_output_tokens']/1000:.1f} | {r['mean_agent_steps']:.1f} | {r['mean_duration_seconds']/60:.1f} | {peak} | {r['context_gate']} |")
lines += ['', '## Marginal returns from raising effort', '', '| Model | Effort change | Score change (pp) | Site cost change | Output change |', '|---|---|---:|---:|---:|']
for model in MODELS:
    group = [r for r in rows if r['model'] == model]
    for a,b in zip(group,group[1:]):
        lines.append(f"| {model} | {a['reasoning_effort']} → {b['reasoning_effort']} | {100*(b['pass_at_1']-a['pass_at_1']):+.2f} | {100*(b['display_cost']/a['display_cost']-1):+.1f}% | {100*(b['mean_output_tokens']/a['mean_output_tokens']-1):+.1f}% |")
lines += ['', '## Dominance', '', 'Point-estimate dominance only; uncertainty is not a significance test. Comparisons restricted to these 20 GPT configurations.', '', '### Score / site cost / output (context omitted)', '']
for r in rows:
    ds = [name(a) for a in rows if a is not r and dominates(a,r)]
    if ds:
        lines.append('- ' + name(r) + ' dominated by: ' + ', '.join(ds) + '.')
eligible = [r for r in rows if r['context_gate'] == 'pass']
frontier = [r for r in eligible if not any(a is not r and dominates(a,r,True) for a in eligible)]
lines += ['', '### Context-gated four-axis frontier', '', ', '.join(name(r) for r in frontier) + '.', '',
    'Astra excluded from this *computed* frontier only because peak context is missing; no finding of failure or dominance follows. Tail breach frequency cannot be recovered from these medians. Local role validation remains necessary.', '',
    '## Extra retained metrics', '',
    'The JSON snapshot retains pass@4, task/attempt counts, CI endpoints and method, median cost/output/input/duration/steps, output-to-pass, cumulative mean input/cache, and Astra cache-write/reasoning/compute usage. These are not interchangeable with active context.', '',
    '## Implications', '',
    '- Astra low/medium/high/xhigh deserve comparison; max must justify its higher resource use against high/xhigh.',
    '- Sol high is the highest-scoring GPT-5.6 row passing the 100k median-context gate. Sol xhigh/max, Terra xhigh/max, and Luna xhigh/max fail that gate.',
    '- Do not interpret cheap low-effort Luna/Terra coding scores as proof they fail scout or researcher roles. DeepSWE measures a coding harness, not those role contracts.',
    '- Before issue 13 implementation: include Astra, preserve compute-unit accounting and missing-context states, and distinguish reproduced site repricing from independently current pricing.',
]
(ROOT / 'comparison.md').write_text('\n'.join(lines) + '\n')
(ROOT / 'gpt-comparison.json').write_text(json.dumps(rows, indent=2) + '\n')
print('\n'.join(lines))
